Router:
  port: 8099

Database:
  mysqlConfig:
    dsn: "root:2495592289@tcp(xenova-mysql:3306)/xenova?charset=utf8mb4&parseTime=True&loc=Local"
    defaultStringSize: 256
    disableDatetimePrecision: true

Redis:
  host: xenova-redis  
  port: 6379
  db: 0
  password:   
          
Jwt:
  signingKey: "xenova@2026!!"
  refresh_exp: 72
  token_exp: 24 #小时
  issuer: "xenova"

Email:
  stmp: "smtp.163.com"
  port: 465
  host: "lf1888@163.com"
  pwd: "NRbXt6ybZxtFYsSJ"
