Router:
  port: 8099

Database:
  mysqlConfig:
    dsn: "root:2495592289@tcp(127.0.0.1:3306)/xenova?charset=utf8mb4&parseTime=True&loc=Local"
    defaultStringSize: 256
    disableDatetimePrecision: true

Redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

Jwt:
  signingKey: "xenova@2026!!"

Email:
  stmp: "your stmp server"
  port: "your smtp port"
  host: "your smtp host"
  pwd: "your smtp pwd"
